--------------------------------------------------------
--  1. DDL for Table COMMODITY
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."COMMODITY" 
   (	"COM_ID" NUMBER(*,0), 
	"COM_NAME" VARCHAR2(20 BYTE), 
	"COM_INTRODUCTION" VARCHAR2(2000 BYTE), 
	"COM_ORIPRICE" NUMBER(15,0), 
	"COM_EXPIRATIONDATE" DATE, 
	"COM_UPLOADDATE" DATE, 
	"COM_LEFT" NUMBER(*,0), 
	"COM_RATING" NUMBER(5,0), 
	"STO_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."COMMODITY"."COM_ID" IS 'commodity ID,PK';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY"."COM_NAME" IS 'Commodity name administrator can be modified, the administrator remarks content fusion here';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY"."COM_INTRODUCTION" IS 'Merchants, administrators can be modified';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY"."COM_ORIPRICE" IS 'original cost';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY"."COM_EXPIRATIONDATE" IS 'due date';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY"."COM_UPLOADDATE" IS 'On the shelf time';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY"."COM_LEFT" IS 'Commodity allowance';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY"."COM_RATING" IS 'Product score';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY"."STO_ID" IS 'Merchant ID, FK, quoted from the store table';
--------------------------------------------------------
--  2. DDL for Table ADMINISTRATOR
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."ADMINISTRATOR" 
   (	"ADMIN_ID" NUMBER(*,0), 
	"ADMIN_ACCNUMBER" VARCHAR2(20 BYTE), 
	"ADMIN_PASSWORD" VARCHAR2(20 BYTE), 
	"ADMIN_STATE" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."ADMINISTRATOR"."ADMIN_ID" IS 'PK';
   COMMENT ON COLUMN "C##ADMIN"."ADMINISTRATOR"."ADMIN_PASSWORD" IS 'The table stores the MD5 value of the actual password';
   COMMENT ON COLUMN "C##ADMIN"."ADMINISTRATOR"."ADMIN_STATE" IS '0: Not logged in/1: Logged in';
--------------------------------------------------------
--  3. DDL for Table APPEAL
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."APPEAL" 
   (	"APP_ID" NUMBER(*,0), 
	"APP_MATTERS" NUMBER(1,0), 
	"APP_CONTENT" VARCHAR2(2000 BYTE), 
	"USER_ID" NUMBER(*,0), 
	"COM_ID" NUMBER(*,0), 
	"CMT_ID" NUMBER(*,0), 
	"APP_USERID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."APPEAL"."APP_ID" IS 'PK';
   COMMENT ON COLUMN "C##ADMIN"."APPEAL"."APP_MATTERS" IS '1: Comment/2: Product/3: Merchant/4: Customer';
   COMMENT ON COLUMN "C##ADMIN"."APPEAL"."USER_ID" IS 'FK, nullable, referenced from the user table';
   COMMENT ON COLUMN "C##ADMIN"."APPEAL"."COM_ID" IS 'FK, nullable, referenced from the community table';
   COMMENT ON COLUMN "C##ADMIN"."APPEAL"."CMT_ID" IS 'FK, nullable, referenced from comment table';
   COMMENT ON COLUMN "C##ADMIN"."APPEAL"."APP_USERID" IS 'FK, referenced from the user table';
--------------------------------------------------------
--  4. DDL for Table CHAT
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."CHAT" 
   (	"CHAT_TIME" TIMESTAMP (6), 
	"CUS_ID" NUMBER(1,0), 
	"STORE_ID" NUMBER(1,0), 
	"CHAT_CONTENT" VARCHAR2(2000 BYTE), 
	"CHAT_SENDER" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."CHAT"."CHAT_TIME" IS 'PK';
   COMMENT ON COLUMN "C##ADMIN"."CHAT"."CUS_ID" IS 'PK,FK,Referencing the cus_ID attribute in the customer table';
   COMMENT ON COLUMN "C##ADMIN"."CHAT"."STORE_ID" IS 'PK,FK,Referencing the store_ID attribute in the store table';
   COMMENT ON COLUMN "C##ADMIN"."CHAT"."CHAT_SENDER" IS '0:customer/1:store';
--------------------------------------------------------
--  5. DDL for Table COMMENT_I
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."COMMENT_I" 
   (	"CMT_ID" NUMBER(*,0), 
	"CMT_FATHER" NUMBER(*,0), 
	"CMT_CONTENT" VARCHAR2(2000 BYTE), 
	"CMT_TIME" DATE, 
	"COM_ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."COMMENT_I"."CMT_ID" IS 'PK';
   COMMENT ON COLUMN "C##ADMIN"."COMMENT_I"."CMT_FATHER" IS '0: No parent comment/Non zero: Parent comment ID';
   COMMENT ON COLUMN "C##ADMIN"."COMMENT_I"."COM_ID" IS 'FK, referenced from the community table';
   COMMENT ON COLUMN "C##ADMIN"."COMMENT_I"."USER_ID" IS 'FK, referenced from the user table';
--------------------------------------------------------
--  6. DDL for Table BROWSE
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."BROWSE" 
   (	"BRO_TIME_START" TIMESTAMP (6), 
	"BRO_TIME_END" TIMESTAMP (6), 
	"COM_ID" NUMBER(1,0), 
	"BROWSER_ID" NUMBER(1,0), 
	"WHETHER_BUY" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."BROWSE"."BRO_TIME_START" IS 'PK';
   COMMENT ON COLUMN "C##ADMIN"."BROWSE"."COM_ID" IS 'PK,FK,"Referencing the com_ID attribute in the commodity table';
   COMMENT ON COLUMN "C##ADMIN"."BROWSE"."BROWSER_ID" IS 'PK,FK,Referencing the cus_ID attribute in the customer table';
   COMMENT ON COLUMN "C##ADMIN"."BROWSE"."WHETHER_BUY" IS '0:havn''t purchase/1:purchase';
--------------------------------------------------------
--  7. DDL for Table COMMODITIES_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."COMMODITIES_CATEGORIES" 
   (	"COM_CATEGORY" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."COMMODITIES_CATEGORIES"."COM_CATEGORY" IS 'The category of a commodity being available in value 	PK';
--------------------------------------------------------
--  8. DDL for Table COMMODITY_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."COMMODITY_CATEGORIES" 
   (	"COM_ID" NUMBER(10,0), 
	"COM_CATEGORY" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."COMMODITY_CATEGORIES"."COM_ID" IS 'PK, FK, as quoted from the commodity table';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY_CATEGORIES"."COM_CATEGORY" IS 'Goods category, FK, quoted from the commodities_categories table';
--------------------------------------------------------
--  9. DDL for Table COMMODITY_IMAGE
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."COMMODITY_IMAGE" 
   (	"COM_ID" NUMBER(1,0), 
	"COM_IMAGE" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."COMMODITY_IMAGE"."COM_ID" IS 'Commodity ID,PK';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY_IMAGE"."COM_IMAGE" IS 'Commodity Image, PK,store using relative path';
--------------------------------------------------------
--  10. DDL for Table COMMODITY_PRICE_CURVE
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."COMMODITY_PRICE_CURVE" 
   (	"COM_ID" NUMBER(1,0), 
	"COM_PC_TIME" DATE, 
	"COM_PC_PRICE" NUMBER(15,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."COMMODITY_PRICE_CURVE"."COM_ID" IS 'Commodity ID,PK';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY_PRICE_CURVE"."COM_PC_TIME" IS 'Time node,PK';
   COMMENT ON COLUMN "C##ADMIN"."COMMODITY_PRICE_CURVE"."COM_PC_PRICE" IS 'Selling Price';
--------------------------------------------------------
--  11. DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."CUSTOMER" 
   (	"CUS_ID" NUMBER(*,0), 
	"CUS_NICKNAME" VARCHAR2(20 BYTE), 
	"CUS_NOTES" VARCHAR2(2000 BYTE), 
	"CUS_PAYPASSWORD" VARCHAR2(20 BYTE), 
	"CUS_STATE" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."CUSTOMER"."CUS_ID" IS 'Customer ID / PK, FK, the same as the corresponding user_ID';
   COMMENT ON COLUMN "C##ADMIN"."CUSTOMER"."CUS_NICKNAME" IS 'nickname';
   COMMENT ON COLUMN "C##ADMIN"."CUSTOMER"."CUS_NOTES" IS 'Personal notes can be set up personally or modified by the administrator';
   COMMENT ON COLUMN "C##ADMIN"."CUSTOMER"."CUS_PAYPASSWORD" IS 'Storage in the payment password table is the md 5 value of the actual password';
   COMMENT ON COLUMN "C##ADMIN"."CUSTOMER"."CUS_STATE" IS 'Account status 0: closed / 1: normal';
--------------------------------------------------------
--  12. DDL for Table CUSTOMER_LOVE
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."CUSTOMER_LOVE" 
   (	"CUS_ID" NUMBER(10,0), 
	"COM_CATEGORY" VARCHAR2(100 BYTE), 
	"CUS_LOVE_WEIGHT" NUMBER(15,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."CUSTOMER_LOVE"."CUS_ID" IS 'Customer ID,PK, FK, is the same as the cus_ID in customer';
   COMMENT ON COLUMN "C##ADMIN"."CUSTOMER_LOVE"."COM_CATEGORY" IS 'Commodity category, PK, FK, is the same as com_category in the commodities_categories table';
   COMMENT ON COLUMN "C##ADMIN"."CUSTOMER_LOVE"."CUS_LOVE_WEIGHT" IS 'Favor label weight, recommendation algorithm to determine';
--------------------------------------------------------
--  13. DDL for Table FAVORITE
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."FAVORITE" 
   (	"COM_ID" NUMBER(1,0), 
	"CUS_ID" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."FAVORITE"."COM_ID" IS 'PK,FK,Referencing the com_ID attribute in the commodity table';
   COMMENT ON COLUMN "C##ADMIN"."FAVORITE"."CUS_ID" IS 'PK,FK,Referencing the cus_ID attribute in the customer table';
--------------------------------------------------------
--  14. DDL for Table INDENT
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."INDENT" 
   (	"IND_ID" NUMBER(*,0), 
	"IND_QUANTITY" NUMBER(*,0), 
	"IND_MONEY" NUMBER(15,0), 
	"IND_CREATIONTIME" DATE, 
	"IND_VERIFICATIONCODE" VARCHAR2(50 BYTE), 
	"IND_NOTES" VARCHAR2(2000 BYTE), 
	"IND_STATE" NUMBER(1,0), 
	"IND_RATING" NUMBER(15,0), 
	"CUS_ID" NUMBER(*,0), 
	"COM_ID" NUMBER(*,0), 
	"IND_RTIME" DATE, 
	"IND_RNOTES" VARCHAR2(2000 BYTE), 
	"IND_RMONEY" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."INDENT"."IND_ID" IS 'PK';
   COMMENT ON COLUMN "C##ADMIN"."INDENT"."IND_STATE" IS '0: To be verified/1: Completed/2: Refunded';
   COMMENT ON COLUMN "C##ADMIN"."INDENT"."CUS_ID" IS 'FK, referenced from customer table';
   COMMENT ON COLUMN "C##ADMIN"."INDENT"."COM_ID" IS 'FK, referenced from the community table';
--------------------------------------------------------
--  15. DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."NOTICE" 
   (	"NTC_ID" NUMBER(*,0), 
	"NTC_TIME" DATE, 
	"NTC_CONTENT" VARCHAR2(2000 BYTE), 
	"NTC_STATE" VARCHAR2(1 BYTE), 
	"STO_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."NOTICE"."NTC_ID" IS 'PK';
   COMMENT ON COLUMN "C##ADMIN"."NOTICE"."NTC_STATE" IS '0: Not displayed/1: Displayed';
   COMMENT ON COLUMN "C##ADMIN"."NOTICE"."STO_ID" IS 'FK, referenced from store table';
--------------------------------------------------------
--  16. DDL for Table SCREENSHOT
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."SCREENSHOT" 
   (	"APP_ID" NUMBER(1,0), 
	"SCT_IMAGE" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."SCREENSHOT"."APP_ID" IS 'PK';
   COMMENT ON COLUMN "C##ADMIN"."SCREENSHOT"."SCT_IMAGE" IS 'PK,store using relative path';
--------------------------------------------------------
--  17. DDL for Table STORE
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."STORE" 
   (	"STO_ID" NUMBER(10,0), 
	"STO_NAME" VARCHAR2(20 BYTE), 
	"STO_INTRODUCTION" VARCHAR2(2000 BYTE), 
	"STO_LICENSEIMG" VARCHAR2(20 BYTE), 
	"STO_STATE" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."STORE"."STO_ID" IS 'Merchant ID, PK, FK, is the same as the corresponding user_ID';
   COMMENT ON COLUMN "C##ADMIN"."STORE"."STO_NAME" IS 'Merchant name';
   COMMENT ON COLUMN "C##ADMIN"."STORE"."STO_INTRODUCTION" IS 'Business profile, can be set by the businesses themselves, can also be modified by the administrator';
   COMMENT ON COLUMN "C##ADMIN"."STORE"."STO_LICENSEIMG" IS 'Business executive, according to the image table stored in the image relative path';
   COMMENT ON COLUMN "C##ADMIN"."STORE"."STO_STATE" IS '0: Closed / 1: Normal / 2: to be reviewed';
--------------------------------------------------------
--  18. DDL for Table STORE_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."STORE_CATEGORIES" 
   (	"STORE_ID" NUMBER(10,0), 
	"COM_CATEGORY" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."STORE_CATEGORIES"."STORE_ID" IS 'Merchant IDPK, FK, quoted from the store table��';
   COMMENT ON COLUMN "C##ADMIN"."STORE_CATEGORIES"."COM_CATEGORY" IS 'Product category FK, quoted from table commodities_categories��';
--------------------------------------------------------
--  19. DDL for Table STOREIMAGE
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."STOREIMAGE" 
   (	"STO_ID" NUMBER(*,0), 
	"STO_IMAGE" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."STOREIMAGE"."STO_ID" IS 'PK';
   COMMENT ON COLUMN "C##ADMIN"."STOREIMAGE"."STO_IMAGE" IS 'PK, stored as a relative path';
--------------------------------------------------------
--  20. DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."USERS" 
   (	"USER_PHONE" VARCHAR2(20 BYTE), 
	"USER_PASSWORD" VARCHAR2(20 BYTE), 
	"USER_ADDRESS" VARCHAR2(100 BYTE), 
	"USER_STATE" NUMBER(1,0), 
	"USER_BALANCE" NUMBER(15,0), 
	"USER_REGTIME" DATE, 
	"USER_TYPE" NUMBER(1,0), 
	"USER_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;

   COMMENT ON COLUMN "C##ADMIN"."USERS"."USER_PHONE" IS 'Phone number, not repeatable, unique';
   COMMENT ON COLUMN "C##ADMIN"."USERS"."USER_PASSWORD" IS 'Login password, the table stores the md 5 value of the actual password';
   COMMENT ON COLUMN "C##ADMIN"."USERS"."USER_ADDRESS" IS 'Geographic location, separating strings of geographic information by semicolons, and processing with functions for queries and operation';
   COMMENT ON COLUMN "C##ADMIN"."USERS"."USER_STATE" IS 'Login status, 0: Not login / 1: Login';
   COMMENT ON COLUMN "C##ADMIN"."USERS"."USER_BALANCE" IS 'balance';
   COMMENT ON COLUMN "C##ADMIN"."USERS"."USER_REGTIME" IS 'registration time';
   COMMENT ON COLUMN "C##ADMIN"."USERS"."USER_TYPE" IS 'User type, 0: Customer / 1: merchant';
   COMMENT ON COLUMN "C##ADMIN"."USERS"."USER_ID" IS 'PK';
--------------------------------------------------------
--  DDL for Index COMMODITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."COMMODITY_PK" ON "C##ADMIN"."COMMODITY" ("COM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index ADMINISTRATOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."ADMINISTRATOR_PK" ON "C##ADMIN"."ADMINISTRATOR" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index APPEAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."APPEAL_PK" ON "C##ADMIN"."APPEAL" ("APP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index CHAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CHAT_PK" ON "C##ADMIN"."CHAT" ("CHAT_TIME", "CUS_ID", "STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index COMMENT_I_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."COMMENT_I_PK" ON "C##ADMIN"."COMMENT_I" ("CMT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index BROWSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."BROWSE_PK" ON "C##ADMIN"."BROWSE" ("BRO_TIME_START", "COM_ID", "BROWSER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index COMMODITIES_CATEGORIES$_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."COMMODITIES_CATEGORIES$_PK" ON "C##ADMIN"."COMMODITIES_CATEGORIES" ("COM_CATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index COMMODITY_CATEGORIES$_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."COMMODITY_CATEGORIES$_PK" ON "C##ADMIN"."COMMODITY_CATEGORIES" ("COM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index COMMODITY_IMAGE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."COMMODITY_IMAGE_PK1" ON "C##ADMIN"."COMMODITY_IMAGE" ("COM_ID", "COM_IMAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index COMMODITY_PRICE_CURVE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."COMMODITY_PRICE_CURVE_PK" ON "C##ADMIN"."COMMODITY_PRICE_CURVE" ("COM_ID", "COM_PC_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CUSTOMER_PK" ON "C##ADMIN"."CUSTOMER" ("CUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_LOVE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CUSTOMER_LOVE_PK" ON "C##ADMIN"."CUSTOMER_LOVE" ("CUS_ID", "COM_CATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index FAVORITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."FAVORITE_PK" ON "C##ADMIN"."FAVORITE" ("COM_ID", "CUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index INDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."INDENT_PK" ON "C##ADMIN"."INDENT" ("IND_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index NOTICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."NOTICE_PK" ON "C##ADMIN"."NOTICE" ("NTC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index SCREENSHOT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."SCREENSHOT_PK" ON "C##ADMIN"."SCREENSHOT" ("APP_ID", "SCT_IMAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index STORE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."STORE_PK" ON "C##ADMIN"."STORE" ("STO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index STORE_CATEGORIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."STORE_CATEGORIES_PK" ON "C##ADMIN"."STORE_CATEGORIES" ("STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index STOREIMAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."STOREIMAGE_PK" ON "C##ADMIN"."STOREIMAGE" ("STO_IMAGE", "STO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."USERS_PK" ON "C##ADMIN"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  DDL for Index USERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."USERS_UK1" ON "C##ADMIN"."USERS" ("USER_PHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE" ;
--------------------------------------------------------
--  Constraints for Table COMMODITY
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."COMMODITY" MODIFY ("COM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY" MODIFY ("COM_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY" MODIFY ("COM_INTRODUCTION" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY" MODIFY ("COM_ORIPRICE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY" MODIFY ("COM_EXPIRATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY" MODIFY ("COM_UPLOADDATE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY" MODIFY ("COM_LEFT" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY" MODIFY ("COM_RATING" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY" MODIFY ("STO_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY" ADD CONSTRAINT "COMMODITY_PK" PRIMARY KEY ("COM_ID")
  USING INDEX "C##ADMIN"."COMMODITY_PK"  ENABLE;
  ALTER TABLE "C##ADMIN"."COMMODITY" ADD CONSTRAINT "COMMODITYCHECK" CHECK (COM_EXPIRATIONDATE>COM_UPLOADDATE and COM_LEFT>0) ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMINISTRATOR
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."ADMINISTRATOR" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."ADMINISTRATOR" ADD CONSTRAINT "ADMINISTRATOR_PK" PRIMARY KEY ("ADMIN_ID")
  USING INDEX "C##ADMIN"."ADMINISTRATOR_PK"  ENABLE;
  ALTER TABLE "C##ADMIN"."ADMINISTRATOR" ADD CONSTRAINT "ADMINISTRATOR_CHK1" CHECK (admin_state=0 or admin_state=1) ENABLE;
--------------------------------------------------------
--  Constraints for Table APPEAL
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."APPEAL" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."APPEAL" ADD CONSTRAINT "APPEAL_PK" PRIMARY KEY ("APP_ID")
  USING INDEX "C##ADMIN"."APPEAL_PK"  ENABLE;
  ALTER TABLE "C##ADMIN"."APPEAL" ADD CONSTRAINT "APPEAL_CHK1" CHECK (app_matters=1 or app_matters=2 or app_matters=3 or app_matters=4) ENABLE;
--------------------------------------------------------
--  Constraints for Table CHAT
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."CHAT" MODIFY ("CHAT_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CHAT" MODIFY ("CUS_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CHAT" MODIFY ("STORE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CHAT" ADD CONSTRAINT "CHAT_PK" PRIMARY KEY ("CHAT_TIME", "CUS_ID", "STORE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENT_I
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."COMMENT_I" MODIFY ("CMT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMENT_I" ADD CONSTRAINT "COMMENT_I_PK" PRIMARY KEY ("CMT_ID")
  USING INDEX "C##ADMIN"."COMMENT_I_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BROWSE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."BROWSE" MODIFY ("BRO_TIME_START" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."BROWSE" MODIFY ("BRO_TIME_END" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."BROWSE" MODIFY ("COM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."BROWSE" MODIFY ("BROWSER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."BROWSE" ADD CONSTRAINT "BROWSE_PK" PRIMARY KEY ("BRO_TIME_START", "COM_ID", "BROWSER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMODITIES_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."COMMODITIES_CATEGORIES" MODIFY ("COM_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITIES_CATEGORIES" ADD CONSTRAINT "COMMODITIES_CATEGORIES$_PK" PRIMARY KEY ("COM_CATEGORY")
  USING INDEX "C##ADMIN"."COMMODITIES_CATEGORIES$_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMODITY_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."COMMODITY_CATEGORIES" MODIFY ("COM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY_CATEGORIES" ADD CONSTRAINT "COMMODITY_CATEGORIES$_PK" PRIMARY KEY ("COM_ID")
  USING INDEX "C##ADMIN"."COMMODITY_CATEGORIES$_PK"  ENABLE;
  ALTER TABLE "C##ADMIN"."COMMODITY_CATEGORIES" MODIFY ("COM_CATEGORY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMODITY_IMAGE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."COMMODITY_IMAGE" MODIFY ("COM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY_IMAGE" MODIFY ("COM_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY_IMAGE" ADD CONSTRAINT "COMMODITY_IMAGE_PK1" PRIMARY KEY ("COM_ID", "COM_IMAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMODITY_PRICE_CURVE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."COMMODITY_PRICE_CURVE" MODIFY ("COM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY_PRICE_CURVE" MODIFY ("COM_PC_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."COMMODITY_PRICE_CURVE" ADD CONSTRAINT "COMMODITY_PRICE_CURVE_PK" PRIMARY KEY ("COM_ID", "COM_PC_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."CUSTOMER" MODIFY ("CUS_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUS_ID")
  USING INDEX "C##ADMIN"."CUSTOMER_PK"  ENABLE;
  ALTER TABLE "C##ADMIN"."CUSTOMER" MODIFY ("CUS_NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CUSTOMER" MODIFY ("CUS_NOTES" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CUSTOMER" MODIFY ("CUS_PAYPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CUSTOMER" MODIFY ("CUS_STATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER_LOVE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."CUSTOMER_LOVE" MODIFY ("COM_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CUSTOMER_LOVE" MODIFY ("CUS_LOVE_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CUSTOMER_LOVE" MODIFY ("CUS_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CUSTOMER_LOVE" ADD CONSTRAINT "CUSTOMER_LOVE_PK" PRIMARY KEY ("CUS_ID", "COM_CATEGORY")
  USING INDEX "C##ADMIN"."CUSTOMER_LOVE_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAVORITE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."FAVORITE" MODIFY ("COM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."FAVORITE" MODIFY ("CUS_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."FAVORITE" ADD CONSTRAINT "FAVORITE_PK" PRIMARY KEY ("COM_ID", "CUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INDENT
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."INDENT" MODIFY ("IND_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."INDENT" ADD CONSTRAINT "INDENT_PK" PRIMARY KEY ("IND_ID")
  USING INDEX "C##ADMIN"."INDENT_PK"  ENABLE;
  ALTER TABLE "C##ADMIN"."INDENT" ADD CONSTRAINT "INDENT_CHK1" CHECK (IND_STATE=0 or IND_STATE=1) ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."NOTICE" MODIFY ("NTC_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."NOTICE" ADD CONSTRAINT "NOTICE_PK" PRIMARY KEY ("NTC_ID")
  USING INDEX "C##ADMIN"."NOTICE_PK"  ENABLE;
  ALTER TABLE "C##ADMIN"."NOTICE" ADD CONSTRAINT "NOTICE_CHK1" CHECK (ntc_state=0 or ntc_state=1) ENABLE;
--------------------------------------------------------
--  Constraints for Table SCREENSHOT
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."SCREENSHOT" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."SCREENSHOT" MODIFY ("SCT_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."SCREENSHOT" ADD CONSTRAINT "SCREENSHOT_PK" PRIMARY KEY ("APP_ID", "SCT_IMAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ADMIN_SPACE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STORE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."STORE" MODIFY ("STO_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."STORE" MODIFY ("STO_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."STORE" MODIFY ("STO_INTRODUCTION" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."STORE" MODIFY ("STO_STATE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."STORE" ADD CONSTRAINT "STORE_PK" PRIMARY KEY ("STO_ID")
  USING INDEX "C##ADMIN"."STORE_PK"  ENABLE;
  ALTER TABLE "C##ADMIN"."STORE" MODIFY ("STO_LICENSEIMG" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."STORE" ADD CONSTRAINT "STORE_CHK1" CHECK (sto_state = 1 or sto_state =0 or sto_state=2) ENABLE;
--------------------------------------------------------
--  Constraints for Table STORE_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."STORE_CATEGORIES" MODIFY ("STORE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."STORE_CATEGORIES" MODIFY ("COM_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."STORE_CATEGORIES" ADD CONSTRAINT "STORE_CATEGORIES_PK" PRIMARY KEY ("STORE_ID")
  USING INDEX "C##ADMIN"."STORE_CATEGORIES_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STOREIMAGE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."STOREIMAGE" MODIFY ("STO_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."STOREIMAGE" MODIFY ("STO_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."STOREIMAGE" ADD CONSTRAINT "STOREIMAGE_PK" PRIMARY KEY ("STO_IMAGE", "STO_ID")
  USING INDEX "C##ADMIN"."STOREIMAGE_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USERS" MODIFY ("USER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USERS" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USERS" MODIFY ("USER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USERS" MODIFY ("USER_STATE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USERS" MODIFY ("USER_BALANCE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USERS" MODIFY ("USER_REGTIME" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USERS" MODIFY ("USER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX "C##ADMIN"."USERS_PK"  ENABLE;
  ALTER TABLE "C##ADMIN"."USERS" ADD CONSTRAINT "USERS_UK1" UNIQUE ("USER_PHONE")
  USING INDEX "C##ADMIN"."USERS_UK1"  ENABLE;
  ALTER TABLE "C##ADMIN"."USERS" ADD CONSTRAINT "USERS_CHK1" CHECK (user_state = 1 OR user_state = 0) ENABLE;
  ALTER TABLE "C##ADMIN"."USERS" ADD CONSTRAINT "USERS_CHK2" CHECK (user_type=0 or user_type=1) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMODITY
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."COMMODITY" ADD CONSTRAINT "COMMODITY_FK1" FOREIGN KEY ("STO_ID")
	  REFERENCES "C##ADMIN"."STORE" ("STO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPEAL
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."APPEAL" ADD CONSTRAINT "APPEAL_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##ADMIN"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."APPEAL" ADD CONSTRAINT "APPEAL_FK2" FOREIGN KEY ("APP_USERID")
	  REFERENCES "C##ADMIN"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."APPEAL" ADD CONSTRAINT "APPEAL_FK3" FOREIGN KEY ("CMT_ID")
	  REFERENCES "C##ADMIN"."COMMENT_I" ("CMT_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."APPEAL" ADD CONSTRAINT "APPEAL_FK4" FOREIGN KEY ("COM_ID")
	  REFERENCES "C##ADMIN"."COMMODITY" ("COM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHAT
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."CHAT" ADD CONSTRAINT "CHAT_FK1" FOREIGN KEY ("CUS_ID")
	  REFERENCES "C##ADMIN"."CUSTOMER" ("CUS_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."CHAT" ADD CONSTRAINT "CHAT_FK2" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##ADMIN"."STORE" ("STO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENT_I
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."COMMENT_I" ADD CONSTRAINT "COMMENT_I_FK1" FOREIGN KEY ("COM_ID")
	  REFERENCES "C##ADMIN"."COMMODITY" ("COM_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."COMMENT_I" ADD CONSTRAINT "COMMENT_I_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##ADMIN"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BROWSE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."BROWSE" ADD CONSTRAINT "BROWSE_FK1" FOREIGN KEY ("COM_ID")
	  REFERENCES "C##ADMIN"."COMMODITY" ("COM_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."BROWSE" ADD CONSTRAINT "BROWSE_FK2" FOREIGN KEY ("BROWSER_ID")
	  REFERENCES "C##ADMIN"."CUSTOMER" ("CUS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMODITY_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."COMMODITY_CATEGORIES" ADD CONSTRAINT "COMMODITY_CATEGORIES$_FK1" FOREIGN KEY ("COM_ID")
	  REFERENCES "C##ADMIN"."COMMODITY" ("COM_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."COMMODITY_CATEGORIES" ADD CONSTRAINT "COMMODITY_CATEGORIES$_FK2" FOREIGN KEY ("COM_CATEGORY")
	  REFERENCES "C##ADMIN"."COMMODITIES_CATEGORIES" ("COM_CATEGORY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_FK1" FOREIGN KEY ("CUS_ID")
	  REFERENCES "C##ADMIN"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER_LOVE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."CUSTOMER_LOVE" ADD CONSTRAINT "CUSTOMER_LOVE_FK1" FOREIGN KEY ("CUS_ID")
	  REFERENCES "C##ADMIN"."CUSTOMER" ("CUS_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."CUSTOMER_LOVE" ADD CONSTRAINT "CUSTOMER_LOVE_FK2" FOREIGN KEY ("COM_CATEGORY")
	  REFERENCES "C##ADMIN"."COMMODITIES_CATEGORIES" ("COM_CATEGORY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FAVORITE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."FAVORITE" ADD CONSTRAINT "FAVORITE_FK1" FOREIGN KEY ("COM_ID")
	  REFERENCES "C##ADMIN"."COMMODITY" ("COM_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."FAVORITE" ADD CONSTRAINT "FAVORITE_FK2" FOREIGN KEY ("CUS_ID")
	  REFERENCES "C##ADMIN"."CUSTOMER" ("CUS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INDENT
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."INDENT" ADD CONSTRAINT "INDENT_FK1" FOREIGN KEY ("CUS_ID")
	  REFERENCES "C##ADMIN"."CUSTOMER" ("CUS_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."INDENT" ADD CONSTRAINT "INDENT_FK2" FOREIGN KEY ("COM_ID")
	  REFERENCES "C##ADMIN"."COMMODITY" ("COM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."NOTICE" ADD CONSTRAINT "NOTICE_FK1" FOREIGN KEY ("STO_ID")
	  REFERENCES "C##ADMIN"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STORE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."STORE" ADD CONSTRAINT "STORE_FK1" FOREIGN KEY ("STO_ID")
	  REFERENCES "C##ADMIN"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STORE_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."STORE_CATEGORIES" ADD CONSTRAINT "STORE_CATEGORIES_FK1" FOREIGN KEY ("COM_CATEGORY")
	  REFERENCES "C##ADMIN"."COMMODITIES_CATEGORIES" ("COM_CATEGORY") ENABLE;
